// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbacfhezlxwuhldhzoiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYWNmaGV6bHh3dWhsZGh6b2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTM0OTUsImV4cCI6MjA4ODU2OTQ5NX0.rxs1gDK4qlGK9g-XSCFKnDLZwTigQjE1zoLxgudKP1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});